# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Jesse Engel
tagline:             'plays well with others'
description:         'A place for my thoughts about music, science, and life.'
url:                 http://jesseengel.github.io
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Jesse Engel
  url:               https://twitter.com/mdo
  email:             

# Custom vars
version:             1.0.0
